"""Added price in Cart

Revision ID: 169c614f45c9
Revises: dfb3e550db57
Create Date: 2024-05-21 21:39:16.142713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '169c614f45c9'
down_revision = 'dfb3e550db57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
